### ISSUE TITLE
No license ->  Not safe to use?

### ISSUE THREAD

**Issue by ForestJohnson** [splee/burrower#7]
Have you intentionally omitted a license for this project to retain your copyright?

Folks would like to use it but are not comfortable with using software that has no license included.

**Comment by splee** [comment]
No, not at all; I'm just a little lazy and hadn't thought about it.  I usually use the MIT License, but I'm open to suggestions.

I'll update the project soon, but feel free to use the project in the meantime as if it were under MIT or similar.  I will not ever attempt to retain copyright of this code.

**Comment by splee** [comment]
PR #4 just got merged which contained the MIT license file.
